=== Vallalanikhil/day18prj/books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.booksinfo.com">
<xsd:element name="books">
			<xsd:complexType>
					<xsd:sequence>
							<xsd:sequence>
								<xsd:element name="book" minOccurs="1" maxOccurs="3">
									<xsd:complexType>
										<xsd:sequence>
											<xsd:element name="bid" type="xsd:int"></xsd:element>
											<xsd:element name="bname" type="xsd:string"></xsd:element>
											<xsd:element name="author" type="xsd:string"></xsd:element>
											<xsd:element name="publisher">
											<xsd:complexType>
											<xsd:attribute name="pname" type="xsd:string"></xsd:attribute>
											</xsd:complexType>
											</xsd:element>
										</xsd:sequence>
									</xsd:complexType>
								</xsd:element>
							</xsd:sequence>
					</xsd:sequence>
			</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Vallalanikhil/day18prj/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<b:books xmlns:xi="http://www.w3.org/2001/XMLSchema-instance" xmlns:b="http://www.booksinfo.com" xi:schemaLocation="http://www.booksinfo.com books.xsd">
	<book>
			<bid>520</bid>
			<bname>The Millionair</bname>
			<author>Nikhil</author>
			<publisher pname="Nk publishers">u can see</publisher>
		</book>	
		
		<book>
			<bid>151</bid>
			<bname>The Stranger</bname>
			<author>Nikhil</author>
			<publisher pname="Nk publishers">u can see</publisher>
			</book>
			
			<book>
			<bid>116</bid>
			<bname>The Monster</bname>
			<author>Nikhil</author>
			<publisher pname="Nk publishers">u can see</publisher>
			</book>
</b:books>
